name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          base_indepth: yes
          config_order: base.header, languages
          plugin_languages: yes
          plugin_languages_analysis_timeout: 20
          plugin_languages_analysis_timeout_repositories: 10
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_threshold: 1%
          plugin_languages_indepth: yes
          commits_authoring: leonpaletta, leon@users.noreply.github.com
          plugin_languages_sections: recently-used
      - name: Generate Half-year Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
